language: php

php:
    - 5.3
    - 5.4

env:
    - CAKE_VERSION=master

before_script:
    - git clone --depth 1 --branch $CAKE_VERSION git://github.com/cakephp/cakephp ../cake && cd ../cake
    - mv ../CakePHP-Bootstrap-3-HtmlHelper/View/Helper/BsHelper.php app/View/Helper/BsHelper.php
    - mv ../CakePHP-Bootstrap-3-HtmlHelper/Test/Case/View/Helper/BsHelperTest.php app/Test/Case/View/Helper/BsHelperTest.php
    - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
    - echo "<?php
        class DATABASE_CONFIG {
        public \$test = array(
          'persistent' => false,
          'host' => '',
          'login' => '',
          'password' => '',
          'database' => 'cakephp_test',
          'prefix' => ''
        );
        }" > ../cake/app/Config/database.php

script:
    - ./lib/Cake/Console/cake test app View/Helper/BsHelper --stderr